from __future__ import annotations

from strava.models._enums import ActivityType, SportType
from strava.models.activities import (
    ActivityZone,
    ClubActivity,
    Comment,
    DetailedActivity,
    Lap,
    MetaActivity,
    SummaryActivity,
    UpdatableActivity,
)
from strava.models.athletes import (
    ClubAthlete,
    DetailedAthlete,
    MetaAthlete,
    SummaryAthlete,
)
from strava.models.clubs import DetailedClub, MetaClub, SummaryClub
from strava.models.common import (
    Error,
    Fault,
    PhotosSummary,
    PolylineMap,
    Split,
    TimedZoneRange,
    Waypoint,
    ZoneRange,
)
from strava.models.gear import DetailedGear, SummaryGear
from strava.models.routes import Route
from strava.models.segments import (
    DetailedSegment,
    DetailedSegmentEffort,
    ExplorerResponse,
    ExplorerSegment,
    SummaryPRSegmentEffort,
    SummarySegment,
    SummarySegmentEffort,
)
from strava.models.stats import (
    ActivityStats,
    ActivityTotal,
    HeartRateZoneRanges,
    PowerZoneRanges,
    Zones,
)
from strava.models.streams import (
    AltitudeStream,
    BaseStream,
    CadenceStream,
    DistanceStream,
    HeartrateStream,
    LatLngStream,
    MovingStream,
    PowerStream,
    SmoothGradeStream,
    SmoothVelocityStream,
    StreamSet,
    TemperatureStream,
    TimeStream,
)
from strava.models.uploads import Upload

__all__ = [
    "ActivityStats",
    "ActivityTotal",
    "ActivityType",
    "ActivityZone",
    "AltitudeStream",
    "BaseStream",
    "CadenceStream",
    "ClubActivity",
    "ClubAthlete",
    "Comment",
    "DetailedActivity",
    "DetailedAthlete",
    "DetailedClub",
    "DetailedGear",
    "DetailedSegment",
    "DetailedSegmentEffort",
    "DistanceStream",
    "Error",
    "ExplorerResponse",
    "ExplorerSegment",
    "Fault",
    "HeartRateZoneRanges",
    "HeartrateStream",
    "Lap",
    "LatLngStream",
    "MetaActivity",
    "MetaAthlete",
    "MetaClub",
    "MovingStream",
    "PhotosSummary",
    "PolylineMap",
    "PowerStream",
    "PowerZoneRanges",
    "Route",
    "SmoothGradeStream",
    "SmoothVelocityStream",
    "Split",
    "SportType",
    "StreamSet",
    "SummaryActivity",
    "SummaryAthlete",
    "SummaryClub",
    "SummaryGear",
    "SummaryPRSegmentEffort",
    "SummarySegment",
    "SummarySegmentEffort",
    "TemperatureStream",
    "TimedZoneRange",
    "TimeStream",
    "UpdatableActivity",
    "Upload",
    "Waypoint",
    "Zones",
    "ZoneRange",
]
